internal_interface: eth0

golang:
  version: "1.15.6"
  sha256: 3918e6cc85e7eaaa6f859f1bdbaac772e7a825b0eb423c63d3ae68b21f84b844

node_exporter:
  version: "1.0.1"
  sha256: 3369b76cd2b0ba678b6d618deab320e565c3d93ccb5c2a0d5db51a53857768ae
  port: "9100"

prometheus:
  version: "2.23.0"
  sha256: 0f54cefdb946852947e35d4db8cfce394911ff586486f927c3887db4183cb643
  port: "9090"

prometheus_slurm_exporter:
  version: "0.15"
  sha256: 77893b595093427c6d9be12af8b340d1a22c0017855d570b3d422338853b855c
  port: "9341"

grafana:
  port: "3000"
  base_url: "/monitoring"

traefik:
  version: "2.4.0"
  sha256: 1e8cd14a0c09ba44ba8b44a94441caaf1edc3e043a65a7d43f9c870be47f70aa
  metrics_port: 8082

jupyterhub:
  port: 8000
  base_url: "/"
  hub_environment: jupyterhub
  lab_environment: jupyterlab
  spawner:
    start_timeout: 60  # seconds
  services:
    prometheus: dpsZlpwaAhi9K8kKf4ZPvCJCuL7D25k1
    dask_gateway: CStgn1NN8DogQR1KajuoQfye1qNRqx6zsh
  template_vars:
    hub_title: "This is QHub OnPrem"
    hub_subtitle: "your scalable open source data science laboratory."
    welcome: "have fun."
    logo: "/hub/custom/images/jupyter_qhub_logo.svg"
    primary_color: '#4f4173'
    secondary_color: '#957da6'
    accent_color: '#32C574'
    text_color: "#111111"
    h1_color: "#652e8e"
    h2_color: "#652e8e"


dask_gateway:
  api_port: 8010
  tcp_port: 8011
  environment: dask-gateway

mysql:
  database: slurm
  users:
    - username: slurm
      password: password1
      privileges: '*.*:ALL'

slurm:
  munge_key: eC36WeTj1JKUGyQEcfqkaRO0fDBoyTVHnkn7kE5sOZ1YUYyqWMSp3qeRZEmtEX9B
  config:
    ClusterName: cluster
    # slurmctld options
    SlurmctldPort: 6817
    SlurmctldLogFile: /var/log/slurm-llnl/slurmctld.log
    SlurmctldPidFile: /var/lib/slurm-llnl/slurmctld.pid
    StateSaveLocation: /var/lib/slurm-llnl/slurmctld
    SwitchType: switch/none
    TaskPlugin: task/affinity
    # slurmctld scheduler
    SchedulerType: sched/backfill
    SelectType: select/cons_res
    SelectTypeParameters: CR_CPU_Memory
    # slurmd options
    SlurmdPort: 6818
    SlurmdLogFile: /var/log/slurm-llnl/slurmd.log
    SlurmdPidFile: /var/lib/slurm-llnl/slurmd.pid
    SlurmdSpoolDir: /var/lib/slurm-llnl/slurmd
  dbd:
    # slurmdbd options
    DbdPort: 6819
    LogFile: /var/log/slurm-llnl/slurmdbd.log
    PidFile: /var/lib/slurm-llnl/slurmdbd.pid

enabled_users:
  - username: example-user
    uid: 10000
    fullname: Example User
    email: example-user@example.com
    # mkpasswd --method=sha-512
    # password: example-user
    password: "$6$3aaf4gr8D$2T31r9/GtXM6rVY8oHOejn.sThwhBZehbPZC.ZkN0XJOZUuguR9VnRQRYmqYAt9eW3LgLR21q1kbqSYSEDm5U."
    primary_group: example-user
    groups:
      - users
      - example-user

enabled_groups:
  - name: example-user
    gid: 10000

disabled_users: []
disabled_groups: []

installed_packages: []

# On/Off Features
jupyterhub_ssh:
  enabled: true
  port: 8022

firewall:
  enabled: true
  internal_ip_range: "192.168.0.0/24"

bodo:
  enabled: false
  conda_username: ...
  conda_token: ...
  license: ...

cdsdashboards:
  enabled: true

backup:
  enabled: false
  on_calendar: "daily"
  randomized_delay: "3600"
  environment:
    RESTIC_REPOSITORY: ...
    RESTIC_PASSWORD: ...
